version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: FinalProject
    ports:
      - "8000:8000"
    volumes:
      - FinalProjectBE:/home
    stdin_open: true
    tty: true
  mysql-server:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "5000:80"
    expose:
      - "5000"
volumes:
  FinalProjectBE:
  mysql-data:
  
